### ISSUE TITLE
📝 In search for initial infos

### ISSUE THREAD

**Issue by johannchopin** [monadgroup/FLParser#16]
Hey team 👋 Thanks a lot for your work on this project.

I was just wondering where you got all this info for parsing a `.flp` file as imagine line doesn't seem to give much information about it. Did you find any docs related to it?

Thanks in advance for the response 😄

**Comment by Kaydax** [comment]
It was all done by trial and error done in the past by other projects like this. LMMS and the node parser for flps where used as the base for information. Any new information is found by changing stuff in fl studio, saving, and comparing what changed, then figuring out the general structure of the file

**Comment by johannchopin** [comment]
Oh waouh this really seems to be a painful task 😅 Thanks for your response 👍
