### ISSUE TITLE
new features please

### ISSUE THREAD

**Issue by F11GAR0** [monadgroup/FLParser#5]
function to save a project in version needed
to copy notes from channels in clipboard (if possible, im tryin, but nothing happend(maybe fl studio dont use win clipboard, im not sure ))

**Comment by cpdt** [comment]
Hi, thanks for submitting the issue and thanks for your interest in the project :)

I’m not too sure on what you’re actually asking. Please keep in mind that this project is just a library to read FL Studio project files, it doesn’t have the ability to modify FL itself. With that considered, would you be able to clarify what you’re asking for? Thanks!

**Comment by F11GAR0** [comment]
i mean, make function in Project class to save loaded project but with another version. like:
FLParser.Project proj = Project.Load(path, true);
proj.Save(some_path, "12.5.0.59");

**Comment by cpdt** [comment]
Hey, really sorry about taking so long to reply to this. Unfortunately saving projects is pretty far outside the scope of this library, there's a whole other bag of compatibility and maintenance work that has to be done for something like that.

I'm going to close this issue now, but please let me know if you have any other questions!
