### ISSUE TITLE
CMD(bin) edition, no?

### ISSUE THREAD

**Issue by daniilkorochansky** [monadgroup/FLParser#6]

**Comment by cpdt** [comment]
Hey, sorry for not getting to this sooner. Are you able to clarify what you're looking for? Please keep in mind this is just a library, it doesn't implement any functionality other than taking an FLP file and putting it into some more friendly data structures.

**Comment by cpdt** [comment]
Hey, I'm going to close this for now since I haven't heard anything back from you. Please reopen this or open a new issue if you have any more questions!
