### ISSUE TITLE
Problems trying to understand the format

### ISSUE THREAD

**Issue by JakubKoralewski** [monadgroup/FLParser#9]
I'm curious, how you reversed engineer this, and I'm taking a look at a project file but the header parsing doesn't seem right to me. 

The highlighted part in the image should be equivalent to the 4-byte long `Int16` variable named `type`:

https://github.com/monadgroup/FLParser/blob/7c5e266c8dd74c02057627ea68e635ef06373b89/ProjectParser.cs#L49-L50

![image](https://user-images.githubusercontent.com/43069023/83059324-0505fa00-a05a-11ea-81c0-ee5bb3abda23.png)

Seems like the `type` variable is not being parsed the way it should be, and would throw a wrong type error for this project file?

I'm a bit of a noob in reverse engineering, am I understanding correctly? Is this project file too new a version, corrupted or am I just mistaken?

**Comment by cpdt** [comment]
Hey, I think you might've made a mistake, that line should be reading the 08/09 bytes:

https://github.com/monadgroup/FLParser/blob/7c5e266c8dd74c02057627ea68e635ef06373b89/ProjectParser.cs#L41-L42

This will read the first 4 bytes, 00-03.

https://github.com/monadgroup/FLParser/blob/7c5e266c8dd74c02057627ea68e635ef06373b89/ProjectParser.cs#L44-L47

This will read the next 4 bytes, 04-07 (Int32 is four bytes).

https://github.com/monadgroup/FLParser/blob/7c5e266c8dd74c02057627ea68e635ef06373b89/ProjectParser.cs#L49-L50

So this will then read bytes 08-09 (Int16 is only two bytes).

As for how it was reverse engineered, the basic parsing structure and some of the "event types" were from [andrewrk's Node FL parser library](https://github.com/andrewrk/node-flp) (which is very out of date now) and the rest was just from changing different values in FL and seeing what changed. As far as I'm aware his library was based on an old implementation in LMMS (which doesn't exist anymore afaik) which was based on an old thread somewhere (which I haven't been able to find again) where an Image-Line employee talked about the basic structure. 

I'll close this thread for now, but if you have any other questions please feel free to ask them!

**Comment by JakubKoralewski** [comment]
I see it now, I somehow mistook a byte for 4 bits 😄. 
Thanks for the patience and the detailed answer.

github.com/LMMS/lmms/pull/2904
Seems like it was a licensing problem.
